### ISSUE TITLE
Can't install in Mac OS X 10.13.6

### ISSUE THREAD

**Issue by rilonian** [SFBrand1981/ChessFriend-Fire#2]
I can't install it in Mac OS X 10.13.6.  I have the following sequence in the Terminal.

![Error ChessFriend](https://user-images.githubusercontent.com/40024065/60285680-62f00600-990e-11e9-80dd-014793affffc.png)

I downloaded the compressed file, unzip it, open it in Terminal and typed the command. Unfortunately, it didn't work...

Thank you very much!

**Comment by appletomato** [comment]
Hi, could you try to download the latest release and run the command again? It might also be necessary to install node.js on your mac: https://nodejs.org/en/. Please let me know if you need further help.

**Comment by rilonian** [comment]
I installed Node.js and download the new release and all worked fine! Thank you very much!
